name: Build EarTrumpet

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore EarTrumpet.vs15.sln

    - name: Build EarTrumpet Executable
      shell: cmd
      run: |
        msbuild EarTrumpet/EarTrumpet.csproj /p:Platform=x86 /p:Configuration=Release /p:OutputPath="%GITHUB_WORKSPACE%\artifacts\" -maxcpucount

    - name: Upload Compiled Executable
      uses: actions/upload-artifact@v4
      with:
        name: EarTrumpet-Build
        path: artifacts/
